# Generated by Django 3.2.12 on 2022-02-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('jurisdiction_of_occurrence', models.CharField(max_length=13)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('all_cause', models.IntegerField()),
                ('natural_cause', models.IntegerField()),
                ('septicemia', models.IntegerField()),
                ('malignant_neoplasms', models.IntegerField()),
                ('diabetes_mellitus', models.IntegerField()),
                ('alzheimer_disease', models.IntegerField()),
                ('influenza_and_pneumonia', models.IntegerField()),
                ('chronic_lower_respiratory', models.IntegerField()),
                ('other_diseases_of_respiratory', models.IntegerField()),
                ('nephritis_nephrotic_syndrom', models.IntegerField()),
                ('symptoms_signs_and_abnormal', models.IntegerField()),
                ('diseases_of_heart', models.IntegerField()),
                ('cerebrovascular_diseases', models.IntegerField()),
                ('accidents_unintentional', models.IntegerField()),
                ('motor_vehicle_accidents', models.IntegerField()),
                ('intentional_self_harm_suicide', models.IntegerField()),
                ('assault_homicide', models.IntegerField()),
                ('drug_overdose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encabezados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fieldName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fieldName', models.CharField(max_length=255, null=True)),
                ('totalCasos', models.IntegerField()),
            ],
        ),
    ]
