# Generated by Django 3.2.12 on 2022-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezados',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
